// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductManagementWebAPI.Data;

#nullable disable

namespace ProductManagementWebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductManagementWebAPI.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dell Inspiron 15, Intel Core i5, 16GB RAM, 512GB SSD",
                            Name = "Laptop",
                            Price = 75000.00m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Samsung Galaxy A55, 8GB RAM, 256GB Storage",
                            Name = "Smartphone",
                            Price = 45000.00m,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Logitech M331 Silent Plus Wireless Mouse",
                            Name = "Wireless Mouse",
                            Price = 1500.00m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Redragon K552 RGB Mechanical Gaming Keyboard",
                            Name = "Mechanical Keyboard",
                            Price = 3500.00m,
                            Quantity = 30
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "LG 24-inch Full HD IPS Monitor",
                            Name = "Monitor",
                            Price = 18000.00m,
                            Quantity = 15
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
